spring:
    application:
        name: banklify-backend
    datasource:
      url: jdbc:postgresql://localhost:5432/banklify-db
      username: banklify_user
      password: banklifypassword
      driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true

jwt:
    secret: your_jwt_secret_key
    expiration: 3600000