spring:
    application:
        name: banklify-backend
    datasource:
      url: jdbc:postgresql://localhost:5432/banklify-db
      username: banklify_user
      password: banklifypassword
      driver-class-name: org.postgresql.Driver

jwt:
    secret: c2VjcmV0X2tleV9mb3JfZmluYW5jaWFsX2FwcGxpY2F0aW9uX3Bhc3N3b3JkXzU2NzhJSkdEMjMzQUJDIQ
    expiration: 3600000

logging:
  level:
    root: INFO
    com.afulvio.banklifybackend: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR